# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.1.0
_src_path: gh:radio-aktywne/template-service-generic
accountname: radio-aktywne
description: Broadcast Icecast transmitting ❄️
docs: true
docsurl: https://radio-aktywne.github.io/quokka
envprefix: QUOKKA
imagename: services/quokka
registry: true
releases: true
reponame: quokka
repourl: https://github.com/radio-aktywne/quokka
servicename: quokka
