# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.1.0
_src_path: gh:radio-aktywne/template-service-generic
accountname: radio-aktywne
description: Broadcast Icecast transmitting ❄️
docs: true
docsurl: https://radio-aktywne.github.io/emicast
envprefix: EMICAST
imagename: services/emicast
registry: true
releases: true
reponame: emicast
repourl: https://github.com/radio-aktywne/emicast
servicename: emicast
