# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.7.1
_src_path: gh:radio-aktywne/template-app-generic
accountname: radio-aktywne
appname: emicast
description: Icecast broadcasting ❄️
docs: true
docsurl: https://radio-aktywne.github.io/app-emicast
envprefix: EMICAST
imagename: apps/emicast
registry: true
releases: true
reponame: app-emicast
repourl: https://github.com/radio-aktywne/app-emicast
