services:
  streamcast:
    build:
      context: ./
      network: host
    network_mode: host
    environment:
      - "STREAMCAST__SERVER__HOST=${STREAMCAST__SERVER__HOST:-0.0.0.0}"
      - "STREAMCAST__SERVER__PORT=${STREAMCAST__SERVER__PORT:-8000}"
      - "STREAMCAST__CREDENTIALS__SOURCE__USER=${STREAMCAST__CREDENTIALS__SOURCE__USER:-source}"
      - "STREAMCAST__CREDENTIALS__SOURCE__PASSWORD=${STREAMCAST__CREDENTIALS__SOURCE__PASSWORD:-password}"
      - "STREAMCAST__CREDENTIALS__ADMIN__USER=${STREAMCAST__CREDENTIALS__ADMIN__USER:-admin}"
      - "STREAMCAST__CREDENTIALS__ADMIN__PASSWORD=${STREAMCAST__CREDENTIALS__ADMIN__PASSWORD:-password}"
