services:
  streamcast:
    build:
      context: ./
      network: host
    network_mode: host
    environment:
      - "STREAMCAST_HOST=${STREAMCAST_HOST:-0.0.0.0}"
      - "STREAMCAST_PORT=${STREAMCAST_PORT:-8000}"
      - "STREAMCAST_SOURCE_USER=${STREAMCAST_SOURCE_USER:-source}"
      - "STREAMCAST_SOURCE_PASSWORD=${STREAMCAST_SOURCE_PASSWORD:-password}"
      - "STREAMCAST_ADMIN_USER=${STREAMCAST_ADMIN_USER:-admin}"
      - "STREAMCAST_ADMIN_PASSWORD=${STREAMCAST_ADMIN_PASSWORD:-password}"
