services:
  quokka:
    build:
      context: ./
      network: host
    network_mode: host
    environment:
      - "QUOKKA__SERVER__HOST=${QUOKKA__SERVER__HOST:-0.0.0.0}"
      - "QUOKKA__SERVER__PORT=${QUOKKA__SERVER__PORT:-10000}"
      - "QUOKKA__CREDENTIALS__SOURCE__USER=${QUOKKA__CREDENTIALS__SOURCE__USER:-source}"
      - "QUOKKA__CREDENTIALS__SOURCE__PASSWORD=${QUOKKA__CREDENTIALS__SOURCE__PASSWORD:-password}"
      - "QUOKKA__CREDENTIALS__ADMIN__USER=${QUOKKA__CREDENTIALS__ADMIN__USER:-admin}"
      - "QUOKKA__CREDENTIALS__ADMIN__PASSWORD=${QUOKKA__CREDENTIALS__ADMIN__PASSWORD:-password}"
